### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: no such file or directory while starting container under Windows 10

### ISSUE THREAD

**Issue by pokyah** [OmicsWorkflows/KNIME_docker_vnc#11]
Hi!

Thanks for this great setup! I was looking for a solution to run KNIME + R + Python in a controlled environment and your docker setup perfectly corresponds to my needs. 

I'm able to run your image hosted on docker hub using the default settings of your `./scripts/start_container.bat`. But I'm unable to start an image built on my own machine.

I've for example successfully built the 4.1.2a & 4.1.3a images on my Windows Computer (I simply had to change the download URL for tigervnc in the dockerfiles). But with no success to actually start the containers. I always get this annoying `standard_init_linux.go:228: exec user process caused: no such file or directory` error while executing `./scripts/start_container.bat` while pointing to my local images instead of using the default setting. 

I've already converted all the files in the repo from CRLF to LF, reperformed builds and tried again  `./scripts/start_container.bat` with my own images but ended up with the same error. 

As you mention that the project was tested under Windows 10 I'm curious to know how do you manage to successfully instantiate a container on Windows 10 from an image built under Windows 10.

Any help would be greatly appreciated. 

Thanks for your support

**Comment by pokyah** [comment]
Have finally performed a dos2unix on the whole folder using the following in powershell :

```
wsl.exe
sudo apt-get update
sudo apt-get install dos2unix
find . -type f -print0 | xargs -0 -n 1 -P 4 dos2unix 
```

And it was solved.

**Comment by weiclav** [comment]
Hi and happy you have solved the issue so quickly on your own!

If I got your right, you have build your own docker image using the docker files here with some minor changes. The issues most probably come from that rebuild (not necessarily the changes). The docker files here were not optimized to be run again and again to build the image on the fly reproducibly, but rather to build the docker image once and use the image from the docker hub over and over again on different places. There is not everything version controlled etc.

Btw., there is almost finished new docker image version (4.5.2a) that will be released soon I hope. We took different approach to the docker image build - sequential one. You may want to check the branch [sequential_4.5.2a](https://github.com/OmicsWorkflows/KNIME_docker_vnc/tree/sequential_4.5.2a), yet the read me file has not yet been updated, sorry for that. In short, there is base ubuntu image we use to put several python+R environments in separate docker images and finally to put VNC and KNIME on top of all that to get the final image to be used. Makes the work with the python and R environments much more robust and reproducible.

Take care!

**Comment by pokyah** [comment]
Hi @weiclav and thanks for the support. 

I've already rebuild my own image based on your 4.5.2a branch. Our needs where a little bit different in terms of software version and flexibility. So I have allowed the dockerfile to parse some variables to let the user choose the software versions at build time. 

One other thing that I've configured on the image is [r2u](https://eddelbuettel.github.io/r2u/) which allows to install R packages as precompiled binaries using apt. It makes the builds way much quicker. 

My repo is hosted on our enterprise git server. But if you want I can also push it somewhere on Github so that you can take some inspiration from it. 

Also I think it would be a great contribution to post something about your dockerised Knime solution on a blog post and/or on Knime community Forum. Do you want to handle it or would your prefer that I do it? 

Best regards !
